export type CustomerStatus = "Active" | "Churn Risk" | "Inactive";

export interface Customer {
  id: string;
  name: string;
  company: string;
  email: string;
  phone: string;
  status: CustomerStatus;
  lifetimeValue: number;
  totalOrders: number;
  country: string;
  currency: string;
  defaultPaymentMethod: string;
  paymentMethodType: "card" | "wire" | "ach";
  joinedDate: string;
  lastActivity: string;
}

export const dummyCustomers: Customer[] = [
  {
    id: "CUST-1001",
    name: "Elena Rostova",
    company: "Acme Corp",
    email: "elena@acmecorp.com",
    phone: "+1 (415) 890-1204",
    status: "Active",
    lifetimeValue: 48900.0,
    totalOrders: 14,
    country: "United States",
    currency: "USD",
    defaultPaymentMethod: "Wire Transfer (Fedwire)",
    paymentMethodType: "wire",
    joinedDate: "Jan 12, 2025",
    lastActivity: "May 21, 2026",
  },
  {
    id: "CUST-1002",
    name: "Marcus Vance",
    company: "Linear Technologies",
    email: "finance@linear.app",
    phone: "+1 (650) 412-9931",
    status: "Active",
    lifetimeValue: 31250.0,
    totalOrders: 9,
    country: "United States",
    currency: "USD",
    defaultPaymentMethod: "Visa •••• 4242",
    paymentMethodType: "card",
    joinedDate: "Mar 04, 2025",
    lastActivity: "May 20, 2026",
  },
  {
    id: "CUST-1003",
    name: "Sarah Jenkins",
    company: "Supabase Inc",
    email: "accounting@supabase.io",
    phone: "+65 6712 8901",
    status: "Churn Risk",
    lifetimeValue: 18400.0,
    totalOrders: 6,
    country: "Singapore",
    currency: "USD",
    defaultPaymentMethod: "Mastercard •••• 8812",
    paymentMethodType: "card",
    joinedDate: "Jun 19, 2025",
    lastActivity: "Apr 28, 2026",
  },
  {
    id: "CUST-1004",
    name: "Devon Chen",
    company: "Vercel Enterprise",
    email: "billing@vercel.com",
    phone: "+1 (415) 338-9012",
    status: "Active",
    lifetimeValue: 92400.0,
    totalOrders: 26,
    country: "United States",
    currency: "USD",
    defaultPaymentMethod: "ACH Direct Debit (Chase)",
    paymentMethodType: "ach",
    joinedDate: "Nov 08, 2024",
    lastActivity: "May 19, 2026",
  },
  {
    id: "CUST-1005",
    name: "Chloe Martin",
    company: "Figma Design Inc",
    email: "finance@figma.com",
    phone: "+1 (415) 762-1100",
    status: "Active",
    lifetimeValue: 56200.0,
    totalOrders: 18,
    country: "United States",
    currency: "USD",
    defaultPaymentMethod: "Visa •••• 5543",
    paymentMethodType: "card",
    joinedDate: "Feb 15, 2025",
    lastActivity: "May 18, 2026",
  },
  {
    id: "CUST-1006",
    name: "Arjun Nair",
    company: "Snowflake Data",
    email: "payments@snowflake.com",
    phone: "+1 (650) 902-7711",
    status: "Active",
    lifetimeValue: 64800.0,
    totalOrders: 11,
    country: "United States",
    currency: "USD",
    defaultPaymentMethod: "Fedwire (J.P. Morgan)",
    paymentMethodType: "wire",
    joinedDate: "Aug 22, 2025",
    lastActivity: "May 14, 2026",
  },
  {
    id: "CUST-1007",
    name: "Liam O'Connor",
    company: "Stripe Atlas",
    email: "ops@stripe.com",
    phone: "+353 1 490 2210",
    status: "Active",
    lifetimeValue: 24500.0,
    totalOrders: 8,
    country: "Ireland",
    currency: "USD",
    defaultPaymentMethod: "Mastercard •••• 9011",
    paymentMethodType: "card",
    joinedDate: "Oct 10, 2025",
    lastActivity: "May 12, 2026",
  },
  {
    id: "CUST-1008",
    name: "Aria Takahashi",
    company: "OpenAI Labs",
    email: "aria@openai.com",
    phone: "+1 (415) 604-3321",
    status: "Active",
    lifetimeValue: 124000.0,
    totalOrders: 32,
    country: "United States",
    currency: "USD",
    defaultPaymentMethod: "ACH Direct Debit (Silicon Valley Bank)",
    paymentMethodType: "ach",
    joinedDate: "Jan 15, 2025",
    lastActivity: "May 21, 2026",
  },
  {
    id: "CUST-1009",
    name: "Tobias Becker",
    company: "FinTech Sol Germany",
    email: "tobias@fintech-sol.de",
    phone: "+49 30 9210 4421",
    status: "Inactive",
    lifetimeValue: 8500.0,
    totalOrders: 3,
    country: "Germany",
    currency: "EUR",
    defaultPaymentMethod: "SEPA Direct Debit",
    paymentMethodType: "ach",
    joinedDate: "Dec 01, 2024",
    lastActivity: "Jan 10, 2026",
  },
];
