import type { PaymentMethodType, TimelineStep, Transaction, TransactionStatus } from "@/types";

export type { PaymentMethodType, TimelineStep, Transaction, TransactionStatus };

export const transactions: Transaction[] = [
  {
    id: "TX-9001",
    amount: "4,800.00",
    grossAmount: 4800.0,
    fee: 139.5,
    netAmount: 4660.5,
    currency: "USD",
    paymentMethod: "Wire Transfer (Fedwire)",
    paymentIcon: "wire",
    methodType: "wire",
    description: "Enterprise Annual License - Q2",
    customer: "Acme Corp",
    name: "Acme Corp",
    customerEmail: "billing@acmecorp.com",
    date: "May 21, 2026, 4:16 PM",
    status: "Succeeded",
    timeline: [
      { step: "Created", timestamp: "May 21, 2026, 4:16 PM", done: true },
      { step: "Authorized", timestamp: "May 21, 2026, 4:17 PM", done: true },
      { step: "Captured", timestamp: "May 21, 2026, 4:18 PM", done: true },
      { step: "Settled", timestamp: "May 21, 2026, 4:30 PM", done: true },
    ],
  },
  {
    id: "TX-9002",
    amount: "1,250.00",
    grossAmount: 1250.0,
    fee: 36.55,
    netAmount: 1213.45,
    currency: "USD",
    paymentMethod: "Visa •••• 4242",
    paymentIcon: "visa",
    methodType: "card",
    description: "Pro Tier Monthly Retainer",
    customer: "Linear Technologies",
    name: "Linear Technologies",
    customerEmail: "finance@linear.app",
    date: "May 21, 2026, 3:45 PM",
    status: "Succeeded",
    timeline: [
      { step: "Created", timestamp: "May 21, 2026, 3:45 PM", done: true },
      { step: "Authorized", timestamp: "May 21, 2026, 3:45 PM", done: true },
      { step: "Captured", timestamp: "May 21, 2026, 3:46 PM", done: true },
      { step: "Settled", timestamp: "May 21, 2026, 4:00 PM", done: true },
    ],
  },
  {
    id: "TX-9003",
    amount: "320.50",
    grossAmount: 320.5,
    fee: 9.6,
    netAmount: 310.9,
    currency: "USD",
    paymentMethod: "Mastercard •••• 5555",
    paymentIcon: "mastercard",
    methodType: "card",
    description: "API Usage Overages (1.2M requests)",
    customer: "Supabase Inc",
    name: "Supabase Inc",
    customerEmail: "ops@supabase.io",
    date: "May 21, 2026, 2:10 PM",
    status: "Pending",
    timeline: [
      { step: "Created", timestamp: "May 21, 2026, 2:10 PM", done: true },
      { step: "Authorized", timestamp: "May 21, 2026, 2:11 PM", done: true },
      { step: "Captured", timestamp: "May 21, 2026, 2:15 PM", done: false },
      { step: "Settled", timestamp: "Pending batch settlement", done: false },
    ],
  },
  {
    id: "TX-9004",
    amount: "8,500.00",
    grossAmount: 8500.0,
    fee: 15.0,
    netAmount: 8485.0,
    currency: "USD",
    paymentMethod: "Chase ACH •••• 9102",
    paymentIcon: "ach",
    methodType: "ach",
    description: "Custom Deployment Setup Fee",
    customer: "Vercel Inc",
    name: "Vercel Inc",
    customerEmail: "accounts-payable@vercel.com",
    date: "May 20, 2026, 5:30 PM",
    status: "Succeeded",
    timeline: [
      { step: "Created", timestamp: "May 20, 2026, 5:30 PM", done: true },
      { step: "Authorized", timestamp: "May 20, 2026, 5:32 PM", done: true },
      { step: "Captured", timestamp: "May 20, 2026, 5:35 PM", done: true },
      { step: "Settled", timestamp: "May 21, 2026, 9:00 AM", done: true },
    ],
  },
  {
    id: "TX-9005",
    amount: "85.00",
    grossAmount: 85.0,
    fee: 2.77,
    netAmount: 82.23,
    currency: "USD",
    paymentMethod: "Apple Pay (Amex •••• 1004)",
    paymentIcon: "amex",
    methodType: "wallet",
    description: "Seat Add-on (5 developers)",
    customer: "Jenny Rosen",
    name: "Jenny Rosen",
    customerEmail: "jenny@example.com",
    date: "May 20, 2026, 3:12 PM",
    status: "Succeeded",
    timeline: [
      { step: "Created", timestamp: "May 20, 2026, 3:12 PM", done: true },
      { step: "Authorized", timestamp: "May 20, 2026, 3:12 PM", done: true },
      { step: "Captured", timestamp: "May 20, 2026, 3:13 PM", done: true },
      { step: "Settled", timestamp: "May 20, 2026, 4:00 PM", done: true },
    ],
  },
  {
    id: "TX-9006",
    amount: "2,400.00",
    grossAmount: 2400.0,
    fee: 69.9,
    netAmount: 2330.1,
    currency: "USD",
    paymentMethod: "Visa •••• 8812",
    paymentIcon: "visa",
    methodType: "card",
    description: "Security Audit Package",
    customer: "Retool Systems",
    name: "Retool Systems",
    customerEmail: "security-billing@retool.com",
    date: "May 20, 2026, 11:24 AM",
    status: "Refunded",
    refundedDate: "May 20, 2026, 02:45 PM",
    timeline: [
      { step: "Created", timestamp: "May 20, 2026, 11:24 AM", done: true },
      { step: "Authorized", timestamp: "May 20, 2026, 11:25 AM", done: true },
      { step: "Captured", timestamp: "May 20, 2026, 11:26 AM", done: true },
      { step: "Settled", timestamp: "Refunded to original card", done: true },
    ],
  },
  {
    id: "TX-9007",
    amount: "650.00",
    grossAmount: 650.0,
    fee: 19.15,
    netAmount: 630.85,
    currency: "USD",
    paymentMethod: "Mastercard •••• 3341",
    paymentIcon: "mastercard",
    methodType: "card",
    description: "Enterprise Support SLA",
    customer: "Datadog Inc",
    name: "Datadog Inc",
    customerEmail: "invoices@datadoghq.com",
    date: "May 19, 2026, 4:40 PM",
    status: "Failed",
    declineReason: "Card declined - insufficient funds",
    timeline: [
      { step: "Created", timestamp: "May 19, 2026, 4:40 PM", done: true },
      { step: "Authorized", timestamp: "Failed: insufficient funds", done: false },
      { step: "Captured", timestamp: "Not attempted", done: false },
      { step: "Settled", timestamp: "Not attempted", done: false },
    ],
  },
  {
    id: "TX-9008",
    amount: "15,000.00",
    grossAmount: 15000.0,
    fee: 25.0,
    netAmount: 14975.0,
    currency: "USD",
    paymentMethod: "SVB Wire Transfer",
    paymentIcon: "wire",
    methodType: "wire",
    description: "Multi-Region Dedicated Infrastructure",
    customer: "OpenAI LLC",
    name: "OpenAI LLC",
    customerEmail: "ap@openai.com",
    date: "May 19, 2026, 1:15 PM",
    status: "Succeeded",
    timeline: [
      { step: "Created", timestamp: "May 19, 2026, 1:15 PM", done: true },
      { step: "Authorized", timestamp: "May 19, 2026, 1:20 PM", done: true },
      { step: "Captured", timestamp: "May 19, 2026, 1:25 PM", done: true },
      { step: "Settled", timestamp: "May 19, 2026, 2:00 PM", done: true },
    ],
  },
  {
    id: "TX-9009",
    amount: "1,850.00",
    grossAmount: 1850.0,
    fee: 53.95,
    netAmount: 1796.05,
    currency: "USD",
    paymentMethod: "Visa •••• 9012",
    paymentIcon: "visa",
    methodType: "card",
    description: "Team Workspace Subscription",
    customer: "Figma Inc",
    name: "Figma Inc",
    customerEmail: "payments@figma.com",
    date: "May 18, 2026, 10:05 AM",
    status: "Disputed",
    declineReason: "Chargeback inquiry: Fraudulent transaction reported by cardholder",
    timeline: [
      { step: "Created", timestamp: "May 18, 2026, 10:05 AM", done: true },
      { step: "Authorized", timestamp: "May 18, 2026, 10:06 AM", done: true },
      { step: "Captured", timestamp: "May 18, 2026, 10:07 AM", done: true },
      { step: "Settled", timestamp: "May 18, 2026, 11:30 AM", done: true },
    ],
  },
  {
    id: "TX-9010",
    amount: "45.00",
    grossAmount: 45.0,
    fee: 1.61,
    netAmount: 43.39,
    currency: "USD",
    paymentMethod: "Google Pay (Mastercard •••• 7712)",
    paymentIcon: "mastercard",
    methodType: "wallet",
    description: "Analytics Export Add-on",
    customer: "Notion Labs",
    name: "Notion Labs",
    customerEmail: "billing@makenotion.com",
    date: "May 17, 2026, 3:22 PM",
    status: "Succeeded",
    timeline: [
      { step: "Created", timestamp: "May 17, 2026, 3:22 PM", done: true },
      { step: "Authorized", timestamp: "May 17, 2026, 3:22 PM", done: true },
      { step: "Captured", timestamp: "May 17, 2026, 3:23 PM", done: true },
      { step: "Settled", timestamp: "May 17, 2026, 4:00 PM", done: true },
    ],
  },
  {
    id: "TX-9011",
    amount: "3,100.00",
    grossAmount: 3100.0,
    fee: 8.0,
    netAmount: 3092.0,
    currency: "USD",
    paymentMethod: "Wells Fargo ACH •••• 4491",
    paymentIcon: "ach",
    methodType: "ach",
    description: "Data Warehouse Sync Connector",
    customer: "Ramp Financial",
    name: "Ramp Financial",
    customerEmail: "treasury@ramp.com",
    date: "May 16, 2026, 1:45 PM",
    status: "Uncaptured",
    timeline: [
      { step: "Created", timestamp: "May 16, 2026, 1:45 PM", done: true },
      { step: "Authorized", timestamp: "May 16, 2026, 1:46 PM", done: true },
      { step: "Captured", timestamp: "Awaiting capture trigger", done: false },
      { step: "Settled", timestamp: "Not settled", done: false },
    ],
  },
  {
    id: "TX-9012",
    amount: "540.00",
    grossAmount: 540.0,
    fee: 15.96,
    netAmount: 524.04,
    currency: "USD",
    paymentMethod: "Amex •••• 2019",
    paymentIcon: "amex",
    methodType: "card",
    description: "Developer API Pro Plan",
    customer: "Stripe Payments UK",
    name: "Stripe Payments UK",
    customerEmail: "billing-uk@stripe.com",
    date: "May 15, 2026, 9:15 AM",
    status: "Succeeded",
    timeline: [
      { step: "Created", timestamp: "May 15, 2026, 9:15 AM", done: true },
      { step: "Authorized", timestamp: "May 15, 2026, 9:16 AM", done: true },
      { step: "Captured", timestamp: "May 15, 2026, 9:17 AM", done: true },
      { step: "Settled", timestamp: "May 15, 2026, 10:00 AM", done: true },
    ],
  },
];
